modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"

[[mods]]
modId = "qxsync"
version = "${mod_version}"
displayName = "QXSync"
description = "Inventory sync to QMServer / QMWeb (NeoForge)."
authors = "QX"

[[dependencies.qxsync]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.qxsync]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
